Feature: Added Boundary locator for Rectangular Shape
awslabs/diagram-maker pull request #39
Opened 2021-04-04 01:24 UTC by manevpe

*Issue #, if available:*

*Description of changes:*
Added a new shape type Rectangle.
Added method for Boundary calculation for the intersection of rectangles.
Added a new demo with rectangular shape connectors with boundary setting.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-06 15:38 UTC, sameergoyal commented on src/components/view/View.tsx
> +const getBoundaryCoordinatesForRectangle = (
Can you add a unit test for this?

2021-04-07 18:50 UTC, manevpe commented on src/components/view/View.tsx
> +const getBoundaryCoordinatesForRectangle = (
I've added a couple of snapshot tests.

2021-04-12 10:22 UTC, sameergoyal requested changes
Apologies for the delay in reviewing. Was cross checking the calculations for coordinates and have found a bug. Please fix that and we should be good to merge.

And thanks for contributing to this library! :)

2021-04-12 10:22 UTC, sameergoyal commented on src/components/view/View.tsx
> +      y: sourceSize.height / 2
This should be sourcePosition.y + sourceSize.height if destinationPosition.y is greater than sourcePosition.y and sourcePosition.y if destionationPosition.y is less than sourcePosition.y. I am able to reproduce in your repo this bug when I bring a node exactly perpendicular either horizontally or vertically.

2021-04-12 10:22 UTC, sameergoyal commented on src/components/view/View.tsx
> +      y: sourcePosition.y
Same as above.

2021-04-12 10:22 UTC, sameergoyal commented on src/components/view/View.tsx
> +  // with the rectangle. Use Pitagorean theorem for the calculations.
Minor: Typo. Pythagorus theorem instead of Pitagorean theorem.

2021-04-12 11:20 UTC, sameergoyal commented on src/components/view/View.tsx
> +      y: sourceSize.height / 2
My bad. It should be sourcePosition.y + sourceSize.height/2 (if sourcePosition.y < destinationPosition.y) else sourcePosition.y - sourceSize.height/2 (if sourcePosition.y > destinationPosition.y)

2021-04-12 18:53 UTC, manevpe commented
> Apologies for the delay in reviewing. Was cross checking the calculations for coordinates and have found a bug. Please fix that and we should be good to merge.
> 
> And thanks for contributing to this library! :)

No worries - it found a bug, so it was worth it :) 
I've commited a fix and added a new unit test for those cases.

2021-04-12 18:55 UTC, manevpe commented on src/components/view/View.tsx
> +const getBoundaryCoordinatesForRectangle = (
Done

2021-04-13 06:15 UTC, sameergoyal approved these changes
Looks good to me after the changes.

Thanks for your contribution. We will add this into your next release.

2021-04-13 06:17 UTC, merged